# syntax = docker/dockerfile:1.4

FROM debian:bookworm-20230703

SHELL ["/bin/bash", "-lc"]

RUN apt-get update -q && \
		export DEBIAN_FRONTEND=noninteractive && \
    apt-get install -y --no-install-recommends \ 
		gpg-agent procps curl tar gpg ca-certificates openssl git unzip build-essential libssl-dev libffi-dev libncurses5-dev zlib1g zlib1g-dev libreadline-dev libbz2-dev libsqlite3-dev && \
	apt-get autoremove -y && \
	apt-get clean -y && \
	rm -rf /var/lib/apt/lists/* \
		/root/.gnupg \
		/tmp/library-scripts

RUN git clone --depth 1 "https://github.com/asdf-vm/asdf.git" "$HOME/.asdf" && \
    echo ". $HOME/.asdf/asdf.sh" >> "$HOME/.bashrc" && \
		echo ". $HOME/.asdf/completions/asdf.bash" >> "$HOME/.bashrc"

RUN /bin/bash -lc "\
    source $HOME/.asdf/asdf.sh && \
    asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git && \
    asdf plugin-add yarn && \
    asdf plugin-add awscli && \
    asdf plugin-add python"

WORKDIR /app
COPY --link .tool-versions ./.tool-versions
COPY --link docker-dev-entrypoint.sh ./docker-dev-entrypoint.sh

RUN /bin/bash -lc "\
    source ~/.asdf/asdf.sh && \
		asdf install"

CMD ["/bin/bash", "docker-dev-entrypoint.sh"]
