services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    networks:
      - devcontainer
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: postgres:15.2-bullseye
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: artist
      POSTGRES_USER: artist
      POSTGRES_DB: artist
    networks:
      - devcontainer

  redis:
    restart: unless-stopped
    image: redis:7.0.11-alpine3.18
    networks:
      - devcontainer
    volumes:
      - redis-data:/data
    healthcheck:
      test: "redis-cli ping"
      interval: 5s
      retries: 20

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local

networks:
  devcontainer:
    driver: bridge
