services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:db
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

    # db:
    #   image: mysql/mysql-server:8.0.32
    #   restart: unless-stopped
    #   volumes:
    #     - mysql-data:/var/lib/mysql
    #   environment:
    #     MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    #     MYSQL_ROOT_HOST: "%"
    #     MYSQL_DATABASE: '${DB_DATABASE}'
    #     MYSQL_USER: '${DB_USERNAME}'
    #     MYSQL_PASSWORD: '${DB_PASSWORD}'
    #     MYSQL_ALLOW_EMPTY_PASSWORD: 1
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  mysql-data:
