import { PrismaClient } from '@prisma/client';
import { uuidv7 } from '@kripod/uuidv7';
const prisma = new PrismaClient();

export const prefecture = async () => {
	await prisma.prefectures.createMany({
		data: [
			{ id: uuidv7(), name: '北海道' },
			{ id: uuidv7(), name: '青森県' },
			{ id: uuidv7(), name: '岩手県' },
			{ id: uuidv7(), name: '宮城県' },
			{ id: uuidv7(), name: '秋田県' },
			{ id: uuidv7(), name: '山形県' },
			{ id: uuidv7(), name: '福島県' },
			{ id: uuidv7(), name: '茨城県' },
			{ id: uuidv7(), name: '栃木県' },
			{ id: uuidv7(), name: '群馬県' },
			{ id: uuidv7(), name: '埼玉県' },
			{ id: uuidv7(), name: '千葉県' },
			{ id: uuidv7(), name: '東京都' },
			{ id: uuidv7(), name: '神奈川県' },
			{ id: uuidv7(), name: '新潟県' },
			{ id: uuidv7(), name: '富山県' },
			{ id: uuidv7(), name: '石川県' },
			{ id: uuidv7(), name: '福井県' },
			{ id: uuidv7(), name: '山梨県' },
			{ id: uuidv7(), name: '長野県' },
			{ id: uuidv7(), name: '岐阜県' },
			{ id: uuidv7(), name: '静岡県' },
			{ id: uuidv7(), name: '愛知県' },
			{ id: uuidv7(), name: '三重県' },
			{ id: uuidv7(), name: '滋賀県' },
			{ id: uuidv7(), name: '京都府' },
			{ id: uuidv7(), name: '大阪府' },
			{ id: uuidv7(), name: '兵庫県' },
			{ id: uuidv7(), name: '奈良県' },
			{ id: uuidv7(), name: '和歌山県' },
			{ id: uuidv7(), name: '鳥取県' },
			{ id: uuidv7(), name: '島根県' },
			{ id: uuidv7(), name: '岡山県' },
			{ id: uuidv7(), name: '広島県' },
			{ id: uuidv7(), name: '山口県' },
			{ id: uuidv7(), name: '徳島県' },
			{ id: uuidv7(), name: '香川県' },
			{ id: uuidv7(), name: '愛媛県' },
			{ id: uuidv7(), name: '高知県' },
			{ id: uuidv7(), name: '福岡県' },
			{ id: uuidv7(), name: '佐賀県' },
			{ id: uuidv7(), name: '長崎県' },
			{ id: uuidv7(), name: '熊本県' },
			{ id: uuidv7(), name: '大分県' },
			{ id: uuidv7(), name: '宮崎県' },
			{ id: uuidv7(), name: '鹿児島県' },
			{ id: uuidv7(), name: '沖縄県' },
		],
	});
};
