name: CI
on: workflow_call

jobs:
  Build:
    if: github.event.pull_request.draft == false
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Generate github token
        id: generate_token
        uses: tibdex/github-app-token@v1.8.0 # リリース時にコミットハッシュで固定
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          token: ${{ steps.generate_token.outputs.token }}
      - name: Setup asdf
        uses: asdf-vm/actions/setup@v2
        # 2回目以降エラーが出るが問題なし
        continue-on-error: true
      - name: asdf install
        uses: asdf-vm/actions/install@v2
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build
        run: yarn build

  Lint:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Generate github token
        id: generate_token
        uses: tibdex/github-app-token@v1.8.0 # リリース時にコミットハッシュで固定
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          token: ${{ steps.generate_token.outputs.token }}
      - name: Setup asdf
        uses: asdf-vm/actions/setup@v2
        # 2回目以降エラーが出るが問題なし
        continue-on-error: true
      - name: asdf install
        uses: asdf-vm/actions/install@v2
      - name: Install dependencies
        run: yarn install --immutable
      - name: fmt
        run: yarn fmt
      - name: lint
        run: yarn lint

  DB-Validate:
    if: github.event.pull_request.draft == false
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Generate github token
        id: generate_token
        uses: tibdex/github-app-token@v1.8.0 # リリース時にコミットハッシュで固定
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          token: ${{ steps.generate_token.outputs.token }}
      - name: Setup asdf
        uses: asdf-vm/actions/setup@v2
        # 2回目以降エラーが出るが問題なし
        continue-on-error: true
      - name: asdf install
        uses: asdf-vm/actions/install@v2
      - name: setup env files
        run: |
          cp .env.example .env
      - name: Install dependencies
        run: yarn install --immutable
      - name: Check Format
        # yarn prisma formatの後にgit statusして差分が出たらfail
        run: yarn prisma format && git diff --exit-code
      - name: DB Validate
        run: yarn prisma validate
      - name: ERD check
        run: yarn prisma generate && git diff --exit-code
