name: Image Build and Push
on:
  workflow_call:
    inputs:
      ref:
        description: 'commit or ref to deploy'
        type: string
        required: true
      sha_short:
        description: 'short sha of commit to deploy'
        type: string
        required: true

jobs:
  Build-And-Push:
    if: github.event.pull_request.draft == false
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Generate github token
        id: generate_token
        uses: tibdex/github-app-token@v1.8.0 # リリース時にコミットハッシュで固定
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          token: ${{ steps.generate_token.outputs.token }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.9.1
        with:
          platforms: linux/amd64
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: ${{ steps.buildx.outputs.platforms }}
          provenance: false
          tags: |
            ghcr.io/${{ github.repository_owner }}/artist-backend:${{ inputs.sha_short }}
            ghcr.io/${{ github.repository_owner }}/artist-backend:${{ inputs.ref }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
